# make slides


matrix0:
	cd matrix-in-R && make

matrix1:
	cd matrix-stat-operations1 && make

matrix2:
	cd matrix-stat-operations1 && make

eigen:
	cd matrix-eigen && make

svd:
	cd matrix-svd && make
